{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-deployment.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "generic-deployment.name" . }}
    helm.sh/chart: {{ include "generic-deployment.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.customLabel }}
{{ toYaml .Values.customLabel | indent 4 }}
    {{- end }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}