name: Deploy  

on:
  push:
    branches: [ "main" ]

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.5.0
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/helm-chart-generic

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install helm
      id: install
      uses: Azure/setup-helm@v3
      with:
        version: ${{ env.HELM_VERSION_TO_INSTALL }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
#     - name: Login to acr using helm 1
#       run: |
#         helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

    - name: Save helm chart to local registry
      run: |
        helm chart save ${{ github.workspace }} ${{ env.GCR_IMAGE }}:latest

    - name: Publish chart to acr
      run: |
        helm chart push ${{ env.GCR_IMAGE }}:${{ github.sha }}
